
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author arifin
 */
public class Form_BiodataSiswa extends javax.swing.JFrame {

    /**
     * Creates new form Form_BiodataSiswa
     */
    public Form_BiodataSiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Nis = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Alamat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Gender = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Jurusan = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Tempatlahir = new javax.swing.JTextField();
        Btnsave = new javax.swing.JToggleButton();
        Reset = new javax.swing.JToggleButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Tanggallahir = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelsiswa = new javax.swing.JTable();
        Edit = new javax.swing.JToggleButton();
        Search = new javax.swing.JToggleButton();
        Search1 = new javax.swing.JToggleButton();

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tgl. Berangkat");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Frame Isian");
        setResizable(false);
        getContentPane().setLayout(null);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(51, 153, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("FORM BIODATA SISWA SMK TELKOM");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(0, 20, 700, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Nama Siswa");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 80, 110, 20);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText(":");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(150, 80, 20, 20);

        Nama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 213), 2));
        getContentPane().add(Nama);
        Nama.setBounds(170, 80, 150, 20);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("NISN");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 110, 120, 20);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText(":");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(150, 110, 20, 14);

        Nis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));
        getContentPane().add(Nis);
        Nis.setBounds(170, 110, 150, 20);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Alamat Asal");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(350, 170, 140, 20);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText(":");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(470, 170, 30, 14);

        Alamat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));
        getContentPane().add(Alamat);
        Alamat.setBounds(490, 170, 150, 20);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Alamat Email");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(350, 140, 110, 20);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText(":");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(470, 140, 30, 14);

        Email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));
        getContentPane().add(Email);
        Email.setBounds(490, 140, 150, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Jenis Kelamin");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(350, 110, 100, 20);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText(":");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(470, 110, 30, 14);

        Gender.setBackground(new java.awt.Color(0, 153, 255));
        Gender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderActionPerformed(evt);
            }
        });
        getContentPane().add(Gender);
        Gender.setBounds(490, 110, 150, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Jurusan");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(350, 80, 50, 20);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText(":");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(470, 80, 30, 14);

        Jurusan.setBackground(new java.awt.Color(0, 153, 255));
        Jurusan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Jurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XI RPL 1", "XI RPL 2", "XI RPL 3", "XI RPL 4", "XI RPL 5", "XI RPL 6", " ", " " }));
        Jurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JurusanActionPerformed(evt);
            }
        });
        getContentPane().add(Jurusan);
        Jurusan.setBounds(490, 80, 150, 20);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Tempat Lahir");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(20, 140, 120, 20);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText(":");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(150, 140, 30, 14);

        Tempatlahir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));
        getContentPane().add(Tempatlahir);
        Tempatlahir.setBounds(170, 140, 150, 20);

        Btnsave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btnsave.setText("Save");
        Btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(Btnsave);
        Btnsave.setBounds(50, 400, 80, 23);

        Reset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Reset.setText("Clear");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset);
        Reset.setBounds(160, 400, 80, 23);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText(":");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(150, 170, 10, 14);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Tanggal Lahir");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(20, 170, 120, 20);
        getContentPane().add(Tanggallahir);
        Tanggallahir.setBounds(170, 170, 150, 20);

        tabelsiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Nis", "Tempat lahir", "Tanggal lahir", "Jurusan", "Jenis Kelamin", "Email", "Alamat"
            }
        ));
        jScrollPane1.setViewportView(tabelsiswa);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 230, 700, 150);

        Edit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit);
        Edit.setBounds(370, 400, 80, 23);

        Search.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Search.setText("Delete");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search);
        Search.setBounds(460, 400, 80, 23);

        Search1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Search1.setText("Search");
        Search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search1ActionPerformed(evt);
            }
        });
        getContentPane().add(Search1);
        Search1.setBounds(270, 400, 80, 23);

        setBounds(0, 0, 719, 491);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderActionPerformed
        // TODO add your handling code here:
        if(Gender.getSelectedItem()=="Laki-laki")
        { }
        if(Gender.getSelectedItem()=="Perempuan")
        {  } 
    }//GEN-LAST:event_GenderActionPerformed

    private void BtnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsaveActionPerformed
   
        String nama = Nama.getText();
        int nis = Integer.parseInt(Nis.getText());
        String tempatlahir = Tempatlahir.getText();
        String tanggallahir = Tanggallahir.getDate().toString();
        String jurusan = Jurusan.getSelectedItem().toString();
        String jeniskelamin = Gender.getSelectedItem().toString();
        String alamat_email = Email.getText();
        String alamat_asal = Alamat.getText();
               
        Connection conn=null;
        PreparedStatement siswa=null;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/data_siswamoklet?=convertToNull", "root", "");
            siswa = conn.prepareStatement("insert into tb_siswa values (?,?,?,?,?,?,?,?)");
            siswa.setString(1, nama);
            siswa.setInt(2, nis);
            siswa.setString(3, tempatlahir);
            siswa.setString(4, tanggallahir);
            siswa.setString(5, jurusan);
            siswa.setString(6, jeniskelamin);
            siswa.setString(7, alamat_email);
            siswa.setString(8, alamat_asal);
            
            int i = siswa.executeUpdate();
            if(i>0){
               JOptionPane.showMessageDialog(null,"data berhasil disimpan"); 
            }
            else{
                 JOptionPane.showMessageDialog(null,"data Gagal disimpan");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        
       DefaultTableModel model = (DefaultTableModel) tabelsiswa.getModel();
        model.addRow (new Object[]{nama,nis,tempatlahir,tanggallahir,jurusan,jeniskelamin,alamat_email,alamat_asal});      
        
        
// TODO add your handling code here:

    }//GEN-LAST:event_BtnsaveActionPerformed

    private void JurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JurusanActionPerformed
        // TODO add your handling code here:
        if(Jurusan.getSelectedItem()=="XI RPL 1")
        { }
        if(Jurusan.getSelectedItem()=="XI RPL 2")
        {  }
        if (Jurusan.getSelectedItem()=="XI RPL 3")
        {  }
        if (Jurusan.getSelectedItem()=="XI RPL 4")
        {  }
        if (Jurusan.getSelectedItem()=="XI RPL 5")
        { }
        if (Jurusan.getSelectedItem()=="MXI RPL 6")
        {  }
        
    }//GEN-LAST:event_JurusanActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        Nama.setText("");
        Nis.setText("");
        Tempatlahir.setText("");
        Tanggallahir.getDate();
        Jurusan.setSelectedItem(null);
        Gender.setSelectedItem(null);
        Email.setText("");
        Alamat.setText("");       

// TODO add your handling code here:
    }//GEN-LAST:event_ResetActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
         int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Untuk Update Record ini???","Confirmation",JOptionPane.YES_NO_OPTION);
         try
            {
                String sql="update identitas set nama=?,nis=?,tempatlahir=?,tanggallahir=?,jurusan=?,jeniskelamin=?,email=?,alamat_asal=? where nama='"+Nama.getText()+"',nis='"+Nis.getText()+"'"
                        + ",tempatlahir='"+Tempatlahir.getText()+"',tanggallahir='"+Tanggallahir.getDate()+"'"
                        + ",jurusan='"+Jurusan.getSelectedItem()+"',jeniskelamin='"+Gender.getSelectedItem()+"'"
                        + ",email='"+Email.getText()+"',alamat_asal='"+Alamat.getText()+"'";
                PreparedStatement siswa=koneksi.prepareStatement(sql);
                if(ok==0)
                {
                try
                    {
                        siswa.setString(1,Nama.getText());
                        siswa.setString(2,Nis.getText());
                        siswa.setString(3,Tempatlahir.getText());
                        siswa.setDate(4, (Date) Tanggallahir.getDate());
                        siswa.setString(5, (String) Jurusan.getSelectedItem());
                        siswa.setString(6, (String) Gender.getSelectedItem());
                        siswa.setString(7,Email.getText());
                        siswa.setString(8,Alamat.getText());
                        siswa.executeUpdate();

                        JOptionPane.showMessageDialog(null,"Update Data Sukses");
                    }catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(null, "Update Data Gagal");
                    }
                }
           }catch (Exception e){}

    }//GEN-LAST:event_EditActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
      int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete record ini???", "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
       if (ok==0)
       {
        try
         {
            String sql="delete from identitas where nama='"+Nama.getText()+"'nis='"+Nis.getText()+"'tempatlahir='"+Tempatlahir.getText()+"',tanggallahir='"+Tanggallahir.getDate()+"'"
                        + ",jurusan='"+Jurusan.getSelectedItem()+"',jeniskelamin='"+Gender.getSelectedItem()+"'"
                        + ",email='"+Email.getText()+"',alamat_asal='"+Alamat.getText()+"'";
            PreparedStatement siswa=koneksi.prepareStatement(sql);
            siswa.executeUpdate();
            JOptionPane.showMessageDialog(null, "Delete Data Sukses");
         }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Delete Data Gagal");
        }
       
       }
       
    }//GEN-LAST:event_SearchActionPerformed

    private void Search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_BiodataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_BiodataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_BiodataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_BiodataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_BiodataSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JToggleButton Btnsave;
    private javax.swing.JToggleButton Edit;
    private javax.swing.JTextField Email;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JComboBox<String> Jurusan;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Nis;
    private javax.swing.JToggleButton Reset;
    private javax.swing.JToggleButton Search;
    private javax.swing.JToggleButton Search1;
    private com.toedter.calendar.JDateChooser Tanggallahir;
    private javax.swing.JTextField Tempatlahir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabelsiswa;
    // End of variables declaration//GEN-END:variables
}
